#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the fortyfive_robot usb connection."
echo ""

sudo cp `rospack find fortyfive_robot_bringup`/99-fortyfive_robot-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
